version: '3.6'

services:
  ## 建立 mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
    networks:
      - testnet

  nginx:
    build: "./Dockerfile"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - mysql
    networks:
      - testnet

networks:
  testnet:
    external: true